# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 457)
        MainWindow.setMinimumSize(QtCore.QSize(1028, 457))
        self.MainWindows = QtWidgets.QWidget(MainWindow)
        self.MainWindows.setObjectName("MainWindows")
        self.gridLayout = QtWidgets.QGridLayout(self.MainWindows)
        self.gridLayout.setObjectName("gridLayout")
        self.gridViewerLayout = QtWidgets.QGridLayout()
        self.gridViewerLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridViewerLayout.setSpacing(0)
        self.gridViewerLayout.setObjectName("gridViewerLayout")
        self.frame = QtWidgets.QFrame(self.MainWindows)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VideoWidget = QtWidgets.QGraphicsView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.VideoWidget.sizePolicy().hasHeightForWidth())
        self.VideoWidget.setSizePolicy(sizePolicy)
        self.VideoWidget.setBaseSize(QtCore.QSize(0, 0))
        self.VideoWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.VideoWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.VideoWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.VideoWidget.setBackgroundBrush(brush)
        self.VideoWidget.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.VideoWidget.setCacheMode(QtWidgets.QGraphicsView.CacheNone)
        self.VideoWidget.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.VideoWidget.setObjectName("VideoWidget")
        self.horizontalLayout.addWidget(self.VideoWidget)
        self.GLWidget = QtWidgets.QGraphicsView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.GLWidget.sizePolicy().hasHeightForWidth())
        self.GLWidget.setSizePolicy(sizePolicy)
        self.GLWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GLWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.GLWidget.setBackgroundBrush(brush)
        self.GLWidget.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.GLWidget.setObjectName("GLWidget")
        self.horizontalLayout.addWidget(self.GLWidget)
        self.gridViewerLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridViewerLayout, 0, 0, 1, 1)
        self.BOTTOM = QtWidgets.QSplitter(self.MainWindows)
        self.BOTTOM.setOrientation(QtCore.Qt.Horizontal)
        self.BOTTOM.setOpaqueResize(False)
        self.BOTTOM.setHandleWidth(10)
        self.BOTTOM.setChildrenCollapsible(True)
        self.BOTTOM.setObjectName("BOTTOM")
        self.LEFT = QtWidgets.QSplitter(self.BOTTOM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.LEFT.sizePolicy().hasHeightForWidth())
        self.LEFT.setSizePolicy(sizePolicy)
        self.LEFT.setOrientation(QtCore.Qt.Vertical)
        self.LEFT.setObjectName("LEFT")
        self.layoutWidget = QtWidgets.QWidget(self.LEFT)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.videoProcessTable = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoProcessTable.sizePolicy().hasHeightForWidth())
        self.videoProcessTable.setSizePolicy(sizePolicy)
        self.videoProcessTable.setMaximumSize(QtCore.QSize(16777215, 10))
        self.videoProcessTable.setLineWidth(0)
        self.videoProcessTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.videoProcessTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.videoProcessTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.videoProcessTable.setAutoScroll(False)
        self.videoProcessTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.videoProcessTable.setTabKeyNavigation(False)
        self.videoProcessTable.setProperty("showDropIndicator", False)
        self.videoProcessTable.setDragDropOverwriteMode(False)
        self.videoProcessTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.videoProcessTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.videoProcessTable.setShowGrid(False)
        self.videoProcessTable.setGridStyle(QtCore.Qt.SolidLine)
        self.videoProcessTable.setRowCount(1)
        self.videoProcessTable.setColumnCount(1)
        self.videoProcessTable.setObjectName("videoProcessTable")
        self.videoProcessTable.horizontalHeader().setVisible(False)
        self.videoProcessTable.horizontalHeader().setCascadingSectionResizes(False)
        self.videoProcessTable.horizontalHeader().setDefaultSectionSize(0)
        self.videoProcessTable.horizontalHeader().setHighlightSections(False)
        self.videoProcessTable.horizontalHeader().setMinimumSectionSize(0)
        self.videoProcessTable.horizontalHeader().setSortIndicatorShown(False)
        self.videoProcessTable.horizontalHeader().setStretchLastSection(False)
        self.videoProcessTable.verticalHeader().setVisible(False)
        self.videoProcessTable.verticalHeader().setDefaultSectionSize(10)
        self.videoProcessTable.verticalHeader().setMinimumSectionSize(10)
        self.horizontalLayout_2.addWidget(self.videoProcessTable)
        spacerItem1 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.videoSlider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoSlider.sizePolicy().hasHeightForWidth())
        self.videoSlider.setSizePolicy(sizePolicy)
        self.videoSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.videoSlider.setMaximum(1)
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.videoSlider.setTickInterval(1)
        self.videoSlider.setObjectName("videoSlider")
        self.verticalLayout_3.addWidget(self.videoSlider)
        self.layoutWidget1 = QtWidgets.QWidget(self.LEFT)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.topButtons = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.topButtons.setContentsMargins(0, 0, 0, 0)
        self.topButtons.setSpacing(6)
        self.topButtons.setObjectName("topButtons")
        self.last10Frame_PB = QtWidgets.QPushButton(self.layoutWidget1)
        self.last10Frame_PB.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/last-10frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.last10Frame_PB.setIcon(icon)
        self.last10Frame_PB.setIconSize(QtCore.QSize(16, 16))
        self.last10Frame_PB.setObjectName("last10Frame_PB")
        self.topButtons.addWidget(self.last10Frame_PB)
        self.lastFrame_PB = QtWidgets.QPushButton(self.layoutWidget1)
        self.lastFrame_PB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/last-frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastFrame_PB.setIcon(icon1)
        self.lastFrame_PB.setIconSize(QtCore.QSize(16, 16))
        self.lastFrame_PB.setObjectName("lastFrame_PB")
        self.topButtons.addWidget(self.lastFrame_PB)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topButtons.addItem(spacerItem2)
        self.read_PB = QtWidgets.QPushButton(self.layoutWidget1)
        self.read_PB.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.read_PB.setIcon(icon2)
        self.read_PB.setObjectName("read_PB")
        self.topButtons.addWidget(self.read_PB)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameInfo = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInfo.sizePolicy().hasHeightForWidth())
        self.frameInfo.setSizePolicy(sizePolicy)
        self.frameInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.frameInfo.setObjectName("frameInfo")
        self.verticalLayout_2.addWidget(self.frameInfo)
        self.facesInfo = QtWidgets.QLabel(self.layoutWidget1)
        self.facesInfo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facesInfo.sizePolicy().hasHeightForWidth())
        self.facesInfo.setSizePolicy(sizePolicy)
        self.facesInfo.setMinimumSize(QtCore.QSize(110, 0))
        self.facesInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.facesInfo.setObjectName("facesInfo")
        self.verticalLayout_2.addWidget(self.facesInfo)
        self.topButtons.addLayout(self.verticalLayout_2)
        self.pause_PB = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_PB.sizePolicy().hasHeightForWidth())
        self.pause_PB.setSizePolicy(sizePolicy)
        self.pause_PB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_PB.setIcon(icon3)
        self.pause_PB.setObjectName("pause_PB")
        self.topButtons.addWidget(self.pause_PB)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topButtons.addItem(spacerItem3)
        self.nextFrame_PB = QtWidgets.QPushButton(self.layoutWidget1)
        self.nextFrame_PB.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/next-frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextFrame_PB.setIcon(icon4)
        self.nextFrame_PB.setObjectName("nextFrame_PB")
        self.topButtons.addWidget(self.nextFrame_PB)
        self.next10Frame_PB = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next10Frame_PB.sizePolicy().hasHeightForWidth())
        self.next10Frame_PB.setSizePolicy(sizePolicy)
        self.next10Frame_PB.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/next-10frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next10Frame_PB.setIcon(icon5)
        self.next10Frame_PB.setObjectName("next10Frame_PB")
        self.topButtons.addWidget(self.next10Frame_PB)
        self.layoutWidget2 = QtWidgets.QWidget(self.LEFT)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.bottomButtons = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.bottomButtons.setContentsMargins(0, 0, 0, 0)
        self.bottomButtons.setObjectName("bottomButtons")
        self.square_BT = QtWidgets.QPushButton(self.layoutWidget2)
        self.square_BT.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_BT.sizePolicy().hasHeightForWidth())
        self.square_BT.setSizePolicy(sizePolicy)
        self.square_BT.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/square-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/square-off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/square-off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.square_BT.setIcon(icon6)
        self.square_BT.setCheckable(True)
        self.square_BT.setObjectName("square_BT")
        self.bottomButtons.addWidget(self.square_BT)
        self.coordinates_PB = QtWidgets.QPushButton(self.layoutWidget2)
        self.coordinates_PB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinates_PB.sizePolicy().hasHeightForWidth())
        self.coordinates_PB.setSizePolicy(sizePolicy)
        self.coordinates_PB.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/coordinates-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/coordinates.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/coordinates-off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/coordinates-off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.coordinates_PB.setIcon(icon7)
        self.coordinates_PB.setCheckable(True)
        self.coordinates_PB.setObjectName("coordinates_PB")
        self.bottomButtons.addWidget(self.coordinates_PB)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtons.addItem(spacerItem4)
        self.headPosition_PB = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headPosition_PB.sizePolicy().hasHeightForWidth())
        self.headPosition_PB.setSizePolicy(sizePolicy)
        self.headPosition_PB.setObjectName("headPosition_PB")
        self.bottomButtons.addWidget(self.headPosition_PB)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtons.addItem(spacerItem5)
        self.screenshot_PB = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenshot_PB.sizePolicy().hasHeightForWidth())
        self.screenshot_PB.setSizePolicy(sizePolicy)
        self.screenshot_PB.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshot_PB.setIcon(icon8)
        self.screenshot_PB.setObjectName("screenshot_PB")
        self.bottomButtons.addWidget(self.screenshot_PB)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtons.addItem(spacerItem6)
        self.processAllVideo_PB = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processAllVideo_PB.sizePolicy().hasHeightForWidth())
        self.processAllVideo_PB.setSizePolicy(sizePolicy)
        self.processAllVideo_PB.setObjectName("processAllVideo_PB")
        self.bottomButtons.addWidget(self.processAllVideo_PB)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtons.addItem(spacerItem7)
        self.confidenceLayout = QtWidgets.QHBoxLayout()
        self.confidenceLayout.setObjectName("confidenceLayout")
        self.confidenceTitle = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confidenceTitle.sizePolicy().hasHeightForWidth())
        self.confidenceTitle.setSizePolicy(sizePolicy)
        self.confidenceTitle.setObjectName("confidenceTitle")
        self.confidenceLayout.addWidget(self.confidenceTitle)
        self.confidenceSlider = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confidenceSlider.sizePolicy().hasHeightForWidth())
        self.confidenceSlider.setSizePolicy(sizePolicy)
        self.confidenceSlider.setMaximum(200)
        self.confidenceSlider.setSingleStep(5)
        self.confidenceSlider.setPageStep(5)
        self.confidenceSlider.setProperty("value", 75)
        self.confidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confidenceSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confidenceSlider.setTickInterval(1)
        self.confidenceSlider.setObjectName("confidenceSlider")
        self.confidenceLayout.addWidget(self.confidenceSlider)
        self.confidenceInfo = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confidenceInfo.sizePolicy().hasHeightForWidth())
        self.confidenceInfo.setSizePolicy(sizePolicy)
        self.confidenceInfo.setObjectName("confidenceInfo")
        self.confidenceLayout.addWidget(self.confidenceInfo)
        self.bottomButtons.addLayout(self.confidenceLayout)
        self.RIGHT = QtWidgets.QSplitter(self.BOTTOM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.RIGHT.sizePolicy().hasHeightForWidth())
        self.RIGHT.setSizePolicy(sizePolicy)
        self.RIGHT.setOrientation(QtCore.Qt.Vertical)
        self.RIGHT.setHandleWidth(5)
        self.RIGHT.setObjectName("RIGHT")
        self.layoutWidget3 = QtWidgets.QWidget(self.RIGHT)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.topGLUtils = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.topGLUtils.setContentsMargins(0, 0, 0, 0)
        self.topGLUtils.setObjectName("topGLUtils")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fovyTitle = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fovyTitle.sizePolicy().hasHeightForWidth())
        self.fovyTitle.setSizePolicy(sizePolicy)
        self.fovyTitle.setMinimumSize(QtCore.QSize(70, 0))
        self.fovyTitle.setObjectName("fovyTitle")
        self.horizontalLayout_4.addWidget(self.fovyTitle)
        self.fovySlider = QtWidgets.QSlider(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fovySlider.sizePolicy().hasHeightForWidth())
        self.fovySlider.setSizePolicy(sizePolicy)
        self.fovySlider.setMinimum(0)
        self.fovySlider.setMaximum(180)
        self.fovySlider.setProperty("value", 20)
        self.fovySlider.setOrientation(QtCore.Qt.Horizontal)
        self.fovySlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fovySlider.setTickInterval(45)
        self.fovySlider.setObjectName("fovySlider")
        self.horizontalLayout_4.addWidget(self.fovySlider)
        self.fovyInfo = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fovyInfo.sizePolicy().hasHeightForWidth())
        self.fovyInfo.setSizePolicy(sizePolicy)
        self.fovyInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.fovyInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fovyInfo.setObjectName("fovyInfo")
        self.horizontalLayout_4.addWidget(self.fovyInfo)
        self.topGLUtils.addLayout(self.horizontalLayout_4)
        self.layoutWidget4 = QtWidgets.QWidget(self.RIGHT)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rollTitle = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollTitle.sizePolicy().hasHeightForWidth())
        self.rollTitle.setSizePolicy(sizePolicy)
        self.rollTitle.setMinimumSize(QtCore.QSize(25, 0))
        self.rollTitle.setStyleSheet("color: rgb(0, 153, 0)")
        self.rollTitle.setObjectName("rollTitle")
        self.horizontalLayout_8.addWidget(self.rollTitle)
        self.rollSlider = QtWidgets.QSlider(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollSlider.sizePolicy().hasHeightForWidth())
        self.rollSlider.setSizePolicy(sizePolicy)
        self.rollSlider.setMinimum(-180)
        self.rollSlider.setMaximum(180)
        self.rollSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rollSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.rollSlider.setTickInterval(180)
        self.rollSlider.setObjectName("rollSlider")
        self.horizontalLayout_8.addWidget(self.rollSlider)
        self.rollInfo = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollInfo.sizePolicy().hasHeightForWidth())
        self.rollInfo.setSizePolicy(sizePolicy)
        self.rollInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.rollInfo.setStyleSheet("color: rgb(0, 153, 0)")
        self.rollInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rollInfo.setObjectName("rollInfo")
        self.horizontalLayout_8.addWidget(self.rollInfo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.yawTitle = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yawTitle.sizePolicy().hasHeightForWidth())
        self.yawTitle.setSizePolicy(sizePolicy)
        self.yawTitle.setMinimumSize(QtCore.QSize(25, 0))
        self.yawTitle.setStyleSheet("color: rgb(0, 0, 200)")
        self.yawTitle.setObjectName("yawTitle")
        self.horizontalLayout_7.addWidget(self.yawTitle)
        self.yawSlider = QtWidgets.QSlider(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yawSlider.sizePolicy().hasHeightForWidth())
        self.yawSlider.setSizePolicy(sizePolicy)
        self.yawSlider.setMinimum(-180)
        self.yawSlider.setMaximum(180)
        self.yawSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yawSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.yawSlider.setTickInterval(180)
        self.yawSlider.setObjectName("yawSlider")
        self.horizontalLayout_7.addWidget(self.yawSlider)
        self.yawInfo = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yawInfo.sizePolicy().hasHeightForWidth())
        self.yawInfo.setSizePolicy(sizePolicy)
        self.yawInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.yawInfo.setStyleSheet("color: rgb(0, 0, 200)")
        self.yawInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yawInfo.setObjectName("yawInfo")
        self.horizontalLayout_7.addWidget(self.yawInfo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pitchTitle = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchTitle.sizePolicy().hasHeightForWidth())
        self.pitchTitle.setSizePolicy(sizePolicy)
        self.pitchTitle.setMinimumSize(QtCore.QSize(25, 0))
        self.pitchTitle.setStyleSheet("color: rgb(255, 0, 0)")
        self.pitchTitle.setObjectName("pitchTitle")
        self.horizontalLayout_6.addWidget(self.pitchTitle)
        self.pitchSlider = QtWidgets.QSlider(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchSlider.sizePolicy().hasHeightForWidth())
        self.pitchSlider.setSizePolicy(sizePolicy)
        self.pitchSlider.setMinimum(-180)
        self.pitchSlider.setMaximum(180)
        self.pitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pitchSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.pitchSlider.setTickInterval(180)
        self.pitchSlider.setObjectName("pitchSlider")
        self.horizontalLayout_6.addWidget(self.pitchSlider)
        self.pitchInfo = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchInfo.sizePolicy().hasHeightForWidth())
        self.pitchInfo.setSizePolicy(sizePolicy)
        self.pitchInfo.setMinimumSize(QtCore.QSize(30, 0))
        self.pitchInfo.setStyleSheet("color: rgb(255, 0, 0)")
        self.pitchInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pitchInfo.setObjectName("pitchInfo")
        self.horizontalLayout_6.addWidget(self.pitchInfo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_6)
        self.resetButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon9)
        self.resetButton.setIconSize(QtCore.QSize(10, 10))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.layoutWidget5 = QtWidgets.QWidget(self.RIGHT)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout.addWidget(self.BOTTOM, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.MainWindows)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_video = QtWidgets.QAction(MainWindow)
        self.actionOpen_video.setObjectName("actionOpen_video")
        self.actionOpen_model = QtWidgets.QAction(MainWindow)
        self.actionOpen_model.setObjectName("actionOpen_model")
        self.menuFile.addAction(self.actionOpen_video)
        self.menuFile.addAction(self.actionOpen_model)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoProcessTable.setSortingEnabled(False)
        self.frameInfo.setText(_translate("MainWindow", "Frame: ..."))
        self.facesInfo.setText(_translate("MainWindow", "Frame not process"))
        self.headPosition_PB.setText(_translate("MainWindow", "Get faces"))
        self.processAllVideo_PB.setText(_translate("MainWindow", "Process all"))
        self.confidenceTitle.setText(_translate("MainWindow", "Confidence"))
        self.confidenceInfo.setText(_translate("MainWindow", "0.75"))
        self.fovyTitle.setText(_translate("MainWindow", "Field of view"))
        self.fovyInfo.setText(_translate("MainWindow", "20"))
        self.rollTitle.setText(_translate("MainWindow", "Roll"))
        self.rollInfo.setText(_translate("MainWindow", "0"))
        self.yawTitle.setText(_translate("MainWindow", "Yaw"))
        self.yawInfo.setText(_translate("MainWindow", "0"))
        self.pitchTitle.setText(_translate("MainWindow", "Pitch"))
        self.pitchInfo.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_video.setText(_translate("MainWindow", "Open video..."))
        self.actionOpen_model.setText(_translate("MainWindow", "Open model..."))

from ui import icons_rc
